local parley = require("parley")
local root = vim.fn.tempname()
local function keys(value)
    vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes(value, true, false, true), "x", false)
end
local function chat(line, config, before)
    parley.setup(vim.tbl_extend("force", {
        chat_dir = root .. "/chats", state_dir = root .. "/state", providers = {}, api_keys = {},
    }, config or {}))
    vim.fn.mkdir(parley.config.chat_dir, "p")
    local path = parley.config.chat_dir .. "/2026-03-01-pair.md"
    vim.fn.writefile({ "# topic: pairs", "- file: pair.md", "---", "", line or "" }, path)
    vim.cmd("noautocmd silent edit! " .. vim.fn.fnameescape(path))
    local buf = vim.api.nvim_get_current_buf()
    if before then before(buf) end
    parley.prep_chat(buf, path)
    assert.is_true(parley._prepared_bufs[buf], tostring(parley.not_chat(buf, path)))
    vim.api.nvim_win_set_cursor(0, { 5, 0 })
    return buf
end
local function body() return vim.api.nvim_get_current_line() end

describe("chat double-at pairing", function()
    after_each(function()
        vim.cmd("stopinsert")
        vim.api.nvim_buf_delete(0, { force = true })
        pcall(vim.keymap.del, "i", "@")
    end)
    it("inserts the closers and leaves typing between them", function()
        chat()
        keys("i@@marker<Esc>")
        assert.equals("@@marker@@", body())
        assert.same({ 5, 7 }, vim.api.nvim_win_get_cursor(0))
    end)
    it("skips both closing characters and keeps insertion one undo step", function()
        chat()
        keys("i@@label@@x<Esc>")
        assert.equals("@@label@@x", body())
        keys("u")
        assert.equals("", body())
        keys("<C-r>")
        assert.equals("@@label@@x", body())
    end)
    it("does not add another closing pair when one already follows", function()
        chat("@@@")
        vim.api.nvim_win_set_cursor(0, { 5, 1 })
        keys("i@label<Esc>")
        assert.equals("@@label@@", body())
    end)
    it("repeats a paired insertion with dot", function()
        chat()
        vim.api.nvim_buf_set_lines(0, 5, 5, false, { "" })
        keys("i@@label@@<Esc>")
        keys("j.")
        assert.equals("@@label@@", body())
    end)
    it("pairs twice on the same line", function()
        chat()
        keys("i@@one@@ ordinary text @@two@@!<Esc>")
        assert.equals("@@one@@ ordinary text @@two@@!", body())
    end)
    it("keeps single-at text literal", function()
        chat()
        keys("iuser@example.com @ hello<Esc>")
        assert.equals("user@example.com @ hello", body())
    end)
    it("works after multibyte text", function()
        chat("💬: ")
        keys("A@@label<Esc>")
        assert.equals("💬: @@label@@", body())
    end)
    for _, scope in ipairs({ "global", "buffer" }) do
        it("preserves an existing " .. scope .. " mapping", function()
            chat("", nil, function(buf)
                vim.keymap.set("i", "@", "custom", scope == "buffer" and { buffer = buf } or {})
            end)
            keys("i@<Esc>")
            assert.equals("custom", body())
        end)
    end
    it("respects disabled default mappings", function()
        chat("", { default_keymaps = false })
        keys("i@@x<Esc>")
        assert.equals("@@x", body())
    end)
    it("enables pairing through the explicit app shortcut policy", function()
        local opts = require("parley.starter_config").options({ data = root, state = root .. "/state" })
        assert.is_false(opts.default_keymaps)
        chat("", opts)
        keys("i@@app@@!<Esc>")
        assert.equals("@@app@@!", body())
        keys("A @@next<Esc>")
        assert.equals("@@app@@! @@next@@", body())
    end)
    it("allows disabling pairing independently", function()
        chat("", { chat_shortcut_pair_at = { shortcut = {} } })
        keys("i@@x<Esc>")
        assert.equals("@@x", body())
    end)
    it("preserves an existing mapping for a configured pairing key", function()
        chat("", { chat_shortcut_pair_at = { modes = { "i" }, shortcut = "!" } }, function(buf)
            vim.keymap.set("i", "!", "custom", { buffer = buf })
        end)
        keys("i!<Esc>")
        assert.equals("custom", body())
    end)
    it("leaves ordinary buffers alone", function()
        chat()
        vim.cmd("enew")
        keys("i@@x<Esc>")
        assert.equals("@@x", body())
    end)
    it("prepares only one mapping", function()
        local buf = chat()
        local mapping = vim.fn.maparg("@", "i", false, true)
        parley.prep_chat(buf, vim.api.nvim_buf_get_name(buf))
        assert.equals(mapping.callback, vim.fn.maparg("@", "i", false, true).callback)
        keys("i@@x<Esc>")
        assert.equals("@@x@@", body())
    end)
end)
