local D=require('parley.document')
local buffers={}
local function fixture()
    local buf=vim.api.nvim_create_buf(false,true);buffers[#buffers+1]=buf
    vim.api.nvim_set_current_buf(buf)
    vim.api.nvim_buf_set_lines(buf,0,-1,false,{'first','selected','last'})
    return buf,D.attach(buf,{schedule=false})
end
local function capture(doc,row,first,last)
    return assert(D.capture_user(doc,{operation='native-user',regions={
        {first={row=row,col=first},last={row=row,col=last}}}}))
end
describe('native user source guards',function()
    after_each(function()
        for _,buf in ipairs(buffers)do if vim.api.nvim_buf_is_valid(buf)then vim.api.nvim_buf_delete(buf,{force=true})end end
        buffers={}
    end)
    it('never revives an overlapping guard through equal replacement, undo or redo',function()
        local buf,doc=fixture();local token=capture(doc,1,0,8)
        assert.equals('idle',D.drain(doc,1000).status)
        vim.cmd('let &undolevels=&undolevels')
        vim.api.nvim_buf_set_text(buf,1,0,1,8,{'selected'})
        assert.is_nil(D.resolve_user(doc,token))
        vim.cmd('undo');assert.is_nil(D.resolve_user(doc,token))
        vim.cmd('redo');assert.is_nil(D.resolve_user(doc,token))
        assert.equals('selected',vim.api.nvim_buf_get_lines(buf,1,2,false)[1])
    end)
    it('relocates disjoint column edits and rejects a join at the selected row edge',function()
        local buf,doc=fixture();local token=capture(doc,1,3,8)
        vim.api.nvim_buf_set_text(buf,1,0,1,0,{'++'})
        local resolved=assert(D.resolve_user(doc,token))
        assert.equals(5,resolved.regions[1].first.col)
        assert.equals(10,resolved.regions[1].last.col)
        assert.equals('applied',D.apply_user(doc,token,{patches={{region=1,text='END'}}}).status)
        assert.equals('++selEND',vim.api.nvim_buf_get_lines(buf,1,2,false)[1])
        local edge=capture(doc,1,0,8)
        vim.api.nvim_buf_set_text(buf,0,5,1,0,{''})
        assert.is_nil(D.resolve_user(doc,edge))
    end)
    it('keeps one user transaction undo scope and expires its token before replay',function()
        local buf,doc=fixture()
        local token=assert(D.capture_user(doc,{operation='both',regions={
            {first={row=0,col=0},last={row=0,col=5}},
            {first={row=2,col=0},last={row=2,col=4}}}}))
        local result=D.apply_user(doc,token,{patches={{region=1,text='FIRST'},{region=2,text='LAST'}}})
        assert.equals('applied',result.status);assert.equals(2,#result.receipts)
        for _,receipt in ipairs(result.receipts)do assert.equals('user',receipt.role);assert.is_nil(receipt.owner)end
        vim.cmd('undo')
        assert.same({'first','selected','last'},vim.api.nvim_buf_get_lines(buf,0,-1,false))
        assert.equals('stale',D.apply_user(doc,token,{patches={{region=1,text='bad'}}}).status)
        vim.cmd('redo')
        assert.same({'FIRST','selected','LAST'},vim.api.nvim_buf_get_lines(buf,0,-1,false))
    end)
    it('accounts for every bounded registry slot visit before observer delivery',function()
        local buf,doc=fixture();local token=capture(doc,1,0,8)
        local work={};local Reader=require('parley.line_reader')
        local observer=Reader.set_observer(buf,function(event)if event.source_guards_visited then work[#work+1]=event.source_guards_visited end end)
        vim.api.nvim_buf_set_text(buf,0,0,0,0,{'x'})
        Reader.clear_observer(buf,observer)
        assert.equals(64,D.user_guard_stats(doc).last_visits)
        assert.equals(64,work[#work]);assert.is_table(D.resolve_user(doc,token))
    end)
end)
