local D=require('parley.document')
local F=require('parley.tool_folds')
describe('document indexed fold reconciliation',function()
    local buf,doc,win
    before_each(function()
        buf=vim.api.nvim_create_buf(false,true);vim.api.nvim_set_current_buf(buf)
        win=vim.api.nvim_get_current_win()
        vim.api.nvim_buf_set_lines(buf,0,-1,false,{
            '💬: q','🤖: a','🧠: thought','body','🧠:[END]','plain','💬: next','draft'})
        doc=D.attach(buf,{schedule=false})
        assert.equals('idle',D.drain(doc).status)
        F.setup(buf)
        F.flush(buf)
    end)
    after_each(function() if vim.api.nvim_buf_is_valid(buf) then vim.api.nvim_buf_delete(buf,{force=true}) end end)
    it('folds confirmed sections without full buffer materialization',function()
        assert.equals(3,vim.fn.foldclosed(3));assert.equals(5,vim.fn.foldclosedend(3))
        assert.equals(-1,vim.fn.foldclosed(7))
    end)
    it('does no native fold work while typing the next question',function()
        vim.cmd('3foldopen')
        local events={};F._observer=function(e) events[#events+1]=e end
        vim.api.nvim_buf_set_text(buf,7,5,7,5,{' more'})
        F.flush(buf)
        F._observer=nil
        assert.equals(0,#events)
        assert.equals(-1,vim.fn.foldclosed(3));assert.equals(1,vim.fn.foldlevel(3))
    end)
    it('removes stale folds after marker deletion without folding questions',function()
        vim.api.nvim_buf_set_lines(buf,2,3,false,{})
        D.drain(doc);F.flush(buf)
        assert.equals(0,vim.fn.foldlevel(3))
        assert.equals(0,vim.fn.foldlevel(6))
    end)
    it('keeps an existing fold open through structural repair',function()
        vim.cmd('3foldopen')
        vim.api.nvim_buf_set_lines(buf,5,6,false,{'📝: summary'})
        D.drain(doc);F.flush(buf)
        assert.equals(1,vim.fn.foldlevel(3));assert.equals(-1,vim.fn.foldclosed(3))
        assert.equals(6,vim.fn.foldclosed(6))
    end)
    it('does not clear folds while the affected structure is uncertain',function()
        vim.api.nvim_buf_set_lines(buf,2,3,false,{'plain marker replacement'})
        F.flush(buf)
        assert.equals(1,vim.fn.foldlevel(3))
        D.drain(doc);F.flush(buf)
        assert.equals(0,vim.fn.foldlevel(3))
    end)
end)
