local repo = vim.fn.getcwd()
local scratch
local function run(argv, cwd)
    local result = vim.system(argv, { cwd = cwd or scratch, text = true }):wait()
    assert.are.equal(0, result.code, result.stderr)
    return vim.trim(result.stdout)
end
local function write(path, lines)
    vim.fn.mkdir(vim.fn.fnamemodify(path, ':h'), 'p')
    vim.fn.writefile(lines, path)
end
local function release(publish)
    local argv = { 'sh', repo .. '/scripts/release-parley.sh', 'v2.3.0', scratch .. '/tap' }
    if publish then argv[#argv + 1] = '--publish' end
    return vim.system(argv, { cwd = scratch .. '/source', text = true, env = {
        GIT_CONFIG_GLOBAL = scratch .. '/gitconfig', GIT_CONFIG_NOSYSTEM = '1',
        PACKAGING_ARCHIVES = scratch .. '/archives', PATH = scratch .. '/bin:' .. vim.env.PATH,
    } }):wait()
end
describe('immutable Homebrew release workflow', function()
    before_each(function()
        scratch = vim.fn.tempname()
        vim.fn.mkdir(scratch, 'p')
        write(scratch .. '/gitconfig', { '[user]', 'name = Test', 'email = test@example.invalid',
            '[url "' .. scratch .. '/source.git"]', 'insteadOf = https://github.com/xianxu/parley.nvim.git',
            '[url "' .. scratch .. '/tap.git"]', 'insteadOf = https://github.com/xianxu/homebrew-parley.git' })
        for _, name in ipairs({ 'source', 'tap' }) do
            run({ 'git', 'init', '--bare', scratch .. '/' .. name .. '.git' })
            run({ 'git', 'clone', scratch .. '/' .. name .. '.git', scratch .. '/' .. name })
            run({ 'git', 'config', 'user.name', 'Test' }, scratch .. '/' .. name)
            run({ 'git', 'config', 'user.email', 'test@example.invalid' }, scratch .. '/' .. name)
            write(scratch .. '/' .. name .. '/README', { 'fixture' })
        end
        for _, path in ipairs({ 'packaging/formula.lua', 'packaging/starter-config/init.lua', 'lua/parley/deps.lua' }) do
            write(scratch .. '/source/' .. path, vim.fn.readfile(repo .. '/' .. path))
        end
        write(scratch .. '/source/packaging/parley', { '#!/bin/sh', 'exit 0' })
        write(scratch .. '/source/packaging/launcher.lua', { '-- fixture profile publisher' })
        -- An archive-only registry default proves rendering does not use the checkout registry.
        local deps = vim.fn.readfile(scratch .. '/source/lua/parley/deps.lua')
        deps = vim.split(table.concat(deps, '\n'):gsub('brew = "ripgrep"', 'brew = "archive-ripgrep"'), '\n')
        write(scratch .. '/source/lua/parley/deps.lua', deps)
        for _, name in ipairs({ 'source', 'tap' }) do
            local cwd = scratch .. '/' .. name
            run({ 'git', 'add', '.' }, cwd)
            run({ 'git', 'commit', '-m', 'fixture' }, cwd)
            run({ 'git', 'push', 'origin', 'HEAD' }, cwd)
            run({ 'git', 'remote', 'set-url', 'origin', 'https://github.com/xianxu/' .. (name == 'source' and 'parley.nvim' or 'homebrew-parley') .. '.git' }, cwd)
        end
        run({ 'git', 'tag', 'v2.3.0' }, scratch .. '/source')
        run({ 'git', 'push', scratch .. '/source.git', 'v2.3.0' }, scratch .. '/source')
        vim.fn.mkdir(scratch .. '/archives', 'p')
        run({ 'git', 'archive', '--format=tar.gz', '--prefix=release/', '--output=' .. scratch .. '/archives/v2.3.0.tar.gz', 'v2.3.0' }, scratch .. '/source')
        vim.fn.mkdir(scratch .. '/bin', 'p')
        assert(vim.uv.fs_symlink(repo .. '/tests/fixtures/fake_packaging_curl', scratch .. '/bin/curl'))
    end)
    after_each(function() vim.fn.delete(scratch, 'rf') end)
    it('generates from the tagged archive without committing by default', function()
        local before = run({ 'git', 'rev-parse', 'HEAD' }, scratch .. '/tap')
        local result = release()
        assert.are.equal(0, result.code, result.stderr)
        local formula = table.concat(vim.fn.readfile(scratch .. '/tap/Formula/parley.rb'), '\n')
        if vim.fn.executable('ruby') == 1 then
            run({ 'ruby', '-c', scratch .. '/tap/Formula/parley.rb' })
        end
        assert.is_truthy(formula:find('depends_on "archive-ripgrep"', 1, true))
        assert.are.equal(before, run({ 'git', 'rev-parse', 'HEAD' }, scratch .. '/tap'))
        local digest = run({ 'shasum', '-a', '256', scratch .. '/archives/v2.3.0.tar.gz' }):match('^%w+')
        assert.is_truthy(formula:find('sha256 "' .. digest .. '"', 1, true))
        assert.are.equal(0, release().code)
        assert.are.equal(0, release(true).code)
    end)
    it('publishes only formula and retries identical publication', function()
        local result = release(true)
        assert.are.equal(0, result.code, result.stderr)
        local head = run({ 'git', 'rev-parse', 'HEAD' }, scratch .. '/tap')
        assert.are.equal('Formula/parley.rb', run({ 'git', 'diff-tree', '--no-commit-id', '--name-only', '-r', 'HEAD' }, scratch .. '/tap'))
        result = release(true)
        assert.are.equal(0, result.code, result.stderr)
        assert.are.equal(head, run({ 'git', 'rev-parse', 'HEAD' }, scratch .. '/tap'))
    end)
    it('retries a committed release after an interrupted push', function()
        local hook = scratch .. '/tap.git/hooks/pre-receive'
        write(hook, { '#!/bin/sh', 'exit 1' })
        vim.fn.setfperm(hook, 'rwx------')
        local result = release(true)
        assert.is_true(result.code ~= 0)
        local head = run({ 'git', 'rev-parse', 'HEAD' }, scratch .. '/tap')
        vim.fn.delete(hook)
        result = release(true)
        assert.are.equal(0, result.code, result.stderr)
        assert.are.equal(head, run({ 'git', 'rev-parse', 'HEAD' }, scratch .. '/tap'))
        assert.are.equal(head, run({ 'git', '--git-dir=' .. scratch .. '/tap.git', 'rev-parse', 'HEAD' }))
    end)
    it('fails without mutating the tap when download or archive contents fail', function()
        vim.fn.delete(scratch .. '/archives/v2.3.0.tar.gz')
        assert.is_true(release().code ~= 0)
        assert.are.equal('', run({ 'git', 'status', '--porcelain' }, scratch .. '/tap'))
        run({ 'git', 'archive', '--format=tar.gz', '--prefix=release/', '--output=' .. scratch .. '/archives/v2.3.0.tar.gz', 'v2.3.0', 'README' }, scratch .. '/source')
        local result = release()
        assert.is_true(result.code ~= 0)
        assert.is_truthy(result.stderr:find('tagged archive lacks packaging/formula.lua', 1, true))
        assert.are.equal('', run({ 'git', 'status', '--porcelain' }, scratch .. '/tap'))
    end)
    it('preserves a dirty formula and refuses symlink destinations', function()
        write(scratch .. '/tap/Formula/parley.rb', { 'human edits' })
        assert.is_true(release(true).code ~= 0)
        assert.are.same({ 'human edits' }, vim.fn.readfile(scratch .. '/tap/Formula/parley.rb'))
        vim.fn.delete(scratch .. '/tap/Formula', 'rf')
        vim.fn.mkdir(scratch .. '/outside', 'p')
        assert(vim.uv.fs_symlink(scratch .. '/outside', scratch .. '/tap/Formula'))
        assert.is_true(release().code ~= 0)
        assert.are.equal(0, vim.fn.filereadable(scratch .. '/outside/parley.rb'))
    end)
    it('refuses dirty or wrong tap and moved local tags', function()
        write(scratch .. '/tap/unrelated', { 'dirty' })
        assert.is_true(release().code ~= 0)
        vim.fn.delete(scratch .. '/tap/unrelated')
        run({ 'git', 'remote', 'set-url', 'origin', 'https://github.com/other/homebrew-parley.git' }, scratch .. '/tap')
        assert.is_true(release().code ~= 0)
        run({ 'git', 'remote', 'set-url', 'origin', 'https://github.com/xianxu/homebrew-parley.git' }, scratch .. '/tap')
        write(scratch .. '/source/changed', { 'new' })
        run({ 'git', 'add', '.' }, scratch .. '/source')
        run({ 'git', 'commit', '-m', 'changed' }, scratch .. '/source')
        run({ 'git', 'tag', '-f', 'v2.3.0' }, scratch .. '/source')
        assert.is_true(release().code ~= 0)
    end)
end)
