local controller = require('parley.spell_blink')
local Fake = require('tests.helpers.fake_blink')
local buf, fake
local function local_map(mode, key)
    return vim.api.nvim_buf_call(buf, function() return vim.fn.maparg(key, mode, false, true) end)
end
local function wait_menu()
    assert.is_true(vim.wait(600, function() return fake.visible end, 5), 'spelling menu did not open')
end
local function attach(opts)
    controller.attach(buf, vim.tbl_extend('force', { blink = true, debounce_ms = 10, max_suggest = 9 }, opts or {}), fake)
end
describe('Blink spell controller', function()
    before_each(function()
        buf = vim.api.nvim_create_buf(false, true)
        vim.api.nvim_set_current_buf(buf)
        vim.bo[buf].filetype, vim.bo[buf].spelllang = 'markdown', 'en_us'
        vim.api.nvim_buf_set_lines(buf, 0, -1, false, { 'before teh after' })
        vim.api.nvim_win_set_cursor(0, { 1, 8 })
        fake = Fake.new()
    end)
    after_each(function()
        controller.detach(buf)
        vim.api.nvim_buf_delete(buf, { force = true })
    end)
    it('enables Blink by default independently of legacy typeahead', function()
        local config = require('parley.config')
        assert.is_true(config.chat_spell.blink)
        assert.is_false(config.chat_spell.typeahead)
        assert.equals(180, config.chat_spell.debounce_ms)
    end)
    it('opens only after debounce, admits one whole-word ticket and preserves providers', function()
        attach()
        assert.is_nil(controller.source_target(buf))
        wait_menu()
        assert.same({ 'parley_spell' }, fake.requested_providers)
        assert.same({ 'buffer', 'parley_spell' }, fake.providers)
        local evidence = controller.source_target(buf)
        assert.equals('teh', evidence.word)
        assert.equals(7, evidence.start_col)
        assert.equals(10, evidence.end_col)
        assert.is_true(controller.consume(evidence))
        assert.is_false(controller.consume(evidence))
    end)
    it('dismisses unchanged words, including within-word motion, until leaving them', function()
        attach(); wait_menu()
        local_map('n', '<Esc>').callback()
        vim.api.nvim_win_set_cursor(0, { 1, 9 })
        vim.api.nvim_exec_autocmds('CursorMoved', { buffer = buf })
        vim.wait(60)
        assert.is_false(fake.visible)
        assert.is_nil(controller.source_target(buf))
        vim.api.nvim_win_set_cursor(0, { 1, 6 })
        vim.api.nvim_exec_autocmds('CursorMoved', { buffer = buf })
        vim.wait(20)
        vim.api.nvim_win_set_cursor(0, { 1, 8 })
        vim.api.nvim_exec_autocmds('CursorMoved', { buffer = buf })
        wait_menu()
    end)
    it('invalidates acceptance synchronously even when deferred reads see a return to the same word', function()
        attach(); wait_menu()
        local evidence = controller.source_target(buf)
        for _, col in ipairs({ 1, 8 }) do
            vim.api.nvim_win_set_cursor(0, { 1, col })
            vim.api.nvim_exec_autocmds('CursorMoved', { buffer = buf })
        end
        assert.is_false(controller.consume(evidence))
    end)
    it('keeps acceptance evidence across Blink hide but rejects a subsequent edit', function()
        attach(); wait_menu()
        local evidence = controller.source_target(buf)
        fake.cmp.hide()
        assert.is_true(controller.consume(evidence))
        controller.request(buf); wait_menu()
        evidence = controller.source_target(buf)
        vim.api.nvim_buf_set_text(buf, 0, 7, 0, 10, { 'ten' })
        assert.is_false(controller.consume(evidence))
    end)
    it('leases and restores callback and expression mappings without overwriting user remaps', function()
        local original = function() return 'prior' end
        vim.keymap.set('n', '<CR>', original, { buffer = buf, expr = true, silent = true })
        vim.keymap.set('i', '<Tab>', 'prior', { buffer = buf, expr = true })
        attach(); wait_menu()
        assert.is_false(local_map('n', '<CR>').callback == original)
        vim.keymap.set('n', '<Down>', 'user', { buffer = buf })
        fake.cmp.hide()
        assert.equals(original, local_map('n', '<CR>').callback)
        assert.equals(1, local_map('n', '<CR>').expr)
        assert.equals('prior', local_map('i', '<Tab>').rhs)
        assert.equals('user', local_map('n', '<Down>').rhs)
        assert.is_nil(local_map('n', '<Up>').callback)
    end)
    it('suppresses refresh previews only for the owned context and restores the adapter', function()
        local original = fake.list.get_selection_mode
        attach(); wait_menu()
        assert.is_false(fake.list.get_selection_mode(fake.context).auto_insert)
        assert.is_true(fake.list.get_selection_mode({ id = -1 }).auto_insert)
        local_map('n', '<Tab>').callback()
        assert.is_false(fake.selection.opts.auto_insert)
        controller.detach(buf)
        assert.equals(original, fake.list.get_selection_mode)
    end)
    it('does not publish a late request after detach and permits delayed readiness', function()
        fake.ready = false
        attach()
        vim.wait(30)
        assert.equals(0, fake.shows)
        fake.ready, fake.defer = true, true
        vim.api.nvim_exec_autocmds('BufEnter', { buffer = buf })
        assert.is_true(vim.wait(500, function() return #fake.pending > 0 end, 5))
        controller.detach(buf)
        fake.deliver()
        assert.is_false(fake.visible)
    end)
end)
