local FS=require('parley.tools.filesystem')
local uv=vim.uv or vim.loop

describe('native asynchronous tool filesystem conformance',function()
    local directory
    before_each(function()directory=vim.fn.tempname();vim.fn.mkdir(directory,'p')end)
    after_each(function()vim.fn.delete(directory,'rf')end)
    local function await(start)
        local result;local handle=start(function(value)result=value end)
        assert.is_nil(result,'filesystem completion must be asynchronous')
        assert.is_true(vim.wait(5000,function()return result~=nil end,1))
        return result,handle
    end
    it('preserves exact backup bytes and completes checked writes without blocking a native timer',function()
        local path=directory..'/file';local original=string.rep('old\n',5000)
        local fd=assert(uv.fs_open(path,'wx',420));assert(uv.fs_write(fd,original,0));assert(uv.fs_close(fd))
        local fs=FS.new({chunk_bytes=1024,max_bytes=131072})
        local before=await(function(done)return fs:read(path,done)end)
        assert.equals(original,before.data);assert.equals('known',before.certainty)
        local timer=false;vim.defer_fn(function()timer=true end,1)
        local replacement=string.rep('new\n',5000)
        local result=await(function(done)return fs:write_checked({path=path,content=replacement,
            expected=before.revision,backup_path=path..'.parley-backup.1'},done)end)
        assert.equals('applied',result.effect);assert.equals('known',result.certainty);assert.is_nil(result.error_code)
        assert.is_true(timer);assert.is_true(result.evidence.backup_confirmed)
        local after=await(function(done)return fs:read(path,done)end)
        local backup=await(function(done)return fs:read(path..'.parley-backup.1',done)end)
        assert.equals(replacement,after.data);assert.equals(original,backup.data)
        assert.equals(before.revision.ino,after.revision.ino)
    end)
    it('refuses stale revisions and creates absent files exclusively',function()
        local path=directory..'/new';local fs=FS.new()
        local absent=await(function(done)return fs:stat(path,done)end);assert.is_false(absent.revision.exists)
        local created=await(function(done)return fs:write_checked({path=path,content='new',expected=absent.revision},done)end)
        assert.equals('applied',created.effect)
        local refused=await(function(done)return fs:write_checked({path=path,content='overwrite',expected=absent.revision},done)end)
        assert.equals('conflict',refused.error_code);assert.equals('not_applied',refused.effect)
    end)
end)
