local P=require('parley')
local D=require('parley.document')
local Registry=require('parley.keybinding_registry')
describe('local user edit provenance',function()
    local buf,dir
    before_each(function()
        dir=vim.fn.tempname();vim.fn.mkdir(dir,'p')
        P.setup({chat_dir=dir})
        local path=dir..'/2026-09-15.12-00-00.000.md'
        vim.fn.writefile({'---','topic: example','file: example.md','---','','💬: question',
            '🤖: answer','before 🤖{proposal} after','suffix','💬: next','draft'},path)
        vim.cmd('edit '..vim.fn.fnameescape(path));buf=vim.api.nvim_get_current_buf()
        P._parley_bufs[buf]='chat';P.prep_chat(buf,path)
        local doc=D.get(buf) or D.attach(buf,{schedule=false});assert.equals('idle',D.drain(doc,10000).status)
    end)
    after_each(function()
        if buf and vim.api.nvim_buf_is_valid(buf) then vim.api.nvim_buf_delete(buf,{force=true}) end
        vim.fn.delete(dir,'rf')
    end)
    local function accept()
        vim.api.nvim_win_set_cursor(0,{8,10})
        local key=Registry.key_for('chat_accept_drill_in',P.config)
        local mapping=vim.fn.maparg(key,'n',false,true)
        assert.equals('function',type(mapping.callback));mapping.callback()
    end
    it('preserves a disjoint human edit during the acceptance flash',function()
        accept()
        vim.api.nvim_buf_set_text(buf,10,5,10,5,{' typed'})
        assert.is_true(vim.wait(1500,function()
            return vim.api.nvim_buf_get_lines(buf,7,8,false)[1]=='before proposal after'
        end,10))
        assert.equals('draft typed',vim.api.nvim_buf_get_lines(buf,10,11,false)[1])
    end)
    it('relocates a pending marker after a disjoint inserted row',function()
        accept()
        vim.api.nvim_buf_set_lines(buf,5,5,false,{'human heading'})
        assert.is_true(vim.wait(1500,function()
            return vim.api.nvim_buf_get_lines(buf,8,9,false)[1]=='before proposal after'
        end,10))
        assert.equals('human heading',vim.api.nvim_buf_get_lines(buf,5,6,false)[1])
    end)
    it('rejects a replaced marker even when the bytes are identical',function()
        accept()
        vim.api.nvim_buf_set_lines(buf,7,8,false,{'before 🤖{proposal} after'})
        vim.wait(700,function() return false end,10)
        assert.equals('before 🤖{proposal} after',vim.api.nvim_buf_get_lines(buf,7,8,false)[1])
    end)
    it('does not resurrect a marker deleted during the acceptance flash',function()
        accept()
        vim.api.nvim_buf_set_lines(buf,7,8,false,{'human replacement'})
        vim.wait(700,function() return false end,10)
        assert.equals('human replacement',vim.api.nvim_buf_get_lines(buf,7,8,false)[1])
    end)
end)
