#!/usr/bin/env python3
"""Filesystem-backed converter fixture: mode and call log survive each invocation."""
import json
import os
import sys
import time

args = sys.argv[1:]
mode = os.environ.get('PARLEY_FAKE_SIPS', 'empty')
log = os.environ.get('PARLEY_FAKE_SIPS_LOG')
if log:
    with open(log, 'a', encoding='utf-8') as stream:
        stream.write(json.dumps(args) + '\n')
output = args[args.index('--out') + 1]
if mode == 'slow':
    time.sleep(30)
if mode == 'fail':
    sys.stderr.write('fixture conversion failure\n')
    sys.exit(7)
if mode == 'oversized':
    with open(output, 'wb') as stream:
        for _ in range(32):
            stream.write(b'x' * (1024 * 1024))
elif mode.startswith('ok:'):
    with open(mode[3:], 'rb') as source, open(output, 'wb') as target:
        target.write(source.read())
elif mode == 'garbage':
    with open(output, 'wb') as stream:
        stream.write(b'not a JPEG')
elif mode == 'empty':
    open(output, 'wb').close()
