-- A release-local projection: never resolve the registry through a caller's runtimepath.
local source = debug.getinfo(1, 'S').source:sub(2)
local root = source:match('^(.*)/packaging/formula%.lua$') or '.'
local deps = dofile(root .. '/lua/parley/deps.lua')
local editor = dofile(root .. '/lua/parley/editor_dependencies.lua')
local M = {}

function M.validate_release(release)
    assert(type(release) == 'table', 'release metadata is required')
    assert(type(release.tag) == 'string' and release.tag:match('^v%d+%.%d+%.%d+$'),
        'tag must be an immutable vMAJOR.MINOR.PATCH release')
    assert(type(release.sha256) == 'string' and #release.sha256 == 64
        and release.sha256:match('^[0-9a-f]+$'), 'sha256 must be 64 lowercase hex digits')
    return true
end

local function quote(value)
    return '"' .. value:gsub('\\', '\\\\'):gsub('"', '\\"'):gsub('#{', '\\#{') .. '"'
end

local function resource(name, record, indent)
    return table.concat({
        indent .. 'resource ' .. quote(name) .. ' do',
        indent .. '  url ' .. quote(record.url),
        indent .. '  sha256 ' .. quote(record.sha256),
        indent .. 'end',
    }, '\n')
end

function M.render_formula(release)
    M.validate_release(release)
    local dependencies = { '  depends_on "neovim"' }
    for _, package in ipairs(deps.packages({ sysname = 'Darwin', manager = 'brew' }, 'default')) do
        assert(package:match('^[a-z0-9][a-z0-9@+._/-]*$'), 'unsafe package name in registry')
        if package ~= 'neovim' then
            dependencies[#dependencies + 1] = '  depends_on "' .. package .. '"'
        end
    end
    dependencies[#dependencies + 1] = '  depends_on "python@3.13" => :build'
    local resources, stages, artifacts = {}, {}, {}
    for _, plugin in ipairs(editor.plugins('app')) do
        resources[#resources + 1] = resource('editor-' .. plugin.name, plugin, '  ')
        stages[#stages + 1] = string.format([[    resource(%s).stage do
      (bundle/%s).install Dir["*", ".*"] - [".", "..", ".git"]
    end]], quote('editor-' .. plugin.name), quote('plugins/' .. plugin.name))
    end
    for _, platform in ipairs({ 'macos-arm64', 'macos', 'linux' }) do
        artifacts[platform] = editor.artifact(platform)
    end
    resources[#resources + 1] = table.concat({
        '  on_macos do',
        '    on_arm do', resource('editor-markdown-preview-binary', artifacts['macos-arm64'], '      '), '    end',
        '    on_intel do', resource('editor-markdown-preview-binary', artifacts.macos, '      '), '    end',
        '  end',
        '  on_linux do',
        '    on_intel do', resource('editor-markdown-preview-binary', artifacts.linux, '      '), '    end',
        '  end',
    }, '\n')
    local payloads = {}
    for _, platform in ipairs({ 'macos-arm64', 'macos', 'linux' }) do
        local artifact = artifacts[platform]
        payloads[#payloads + 1] = string.format('      %s => [%s, %s],',
            quote(platform), quote(artifact.member), quote(artifact.output))
    end
    return string.format([[# Generated by parley.nvim packaging/formula.lua; edit the source generator.
class Parley < Formula
  desc "Isolated Neovim chat application"
  homepage "https://github.com/xianxu/parley.nvim"
  url "https://github.com/xianxu/parley.nvim/archive/refs/tags/%s.tar.gz"
  sha256 "%s"
  license "MIT"

%s

%s

  def install
    odie "unsupported editor bundle platform: Linux ARM" if OS.linux? && !Hardware::CPU.intel?
    libexec.install Dir["*", ".*"] - [".", "..", ".git"]
    bundle = libexec/"editor-bundle"
%s
    platform = OS.mac? ? (Hardware::CPU.arm? ? "macos-arm64" : "macos") : "linux"
    preview = {
%s
    }.fetch(platform)
    resource("editor-markdown-preview-binary").stage do
      destination = bundle/preview[1]
      destination.dirname.mkpath
      destination.dirname.install preview[0] => destination.basename.to_s
      destination.chmod 0755
    end
    system Formula["python@3.13"].opt_bin/"python3.13", libexec/"scripts/editor-dependencies.py",
      "--runtime", libexec, "--platform", platform, "--profile", "app",
      "seal", "--bundle", bundle
    (libexec/"packaging/parley").chmod 0755
    (share/"parley/config").install libexec/"packaging/starter-config/init.lua"
    (bin/"parley").write_env_script libexec/"packaging/parley",
      PARLEY_NVIM: Formula["neovim"].opt_bin/"nvim",
      PARLEY_RUNTIME: libexec,
      PARLEY_EDITOR_BUNDLE: libexec/"editor-bundle",
      PARLEY_EDITOR_BUNDLE_INSTALLED: "1",
      PARLEY_STARTER: share/"parley/config/init.lua"
  end

  test do
    ENV["XDG_CONFIG_HOME"] = (testpath/"config").to_s
    assert_match "NVIM", shell_output("#{bin}/parley --version")
    assert_path_exists testpath/"config/parley/init.lua"
  end
end
]], release.tag, release.sha256, table.concat(dependencies, '\n'), table.concat(resources, '\n\n'),
        table.concat(stages, '\n'), table.concat(payloads, '\n'))
end

return M
