-- A release-local projection: never resolve the registry through a caller's runtimepath.
local source = debug.getinfo(1, 'S').source:sub(2)
local root = source:match('^(.*)/packaging/formula%.lua$') or '.'
local deps = dofile(root .. '/lua/parley/deps.lua')
local M = {}

function M.validate_release(release)
    assert(type(release) == 'table', 'release metadata is required')
    assert(type(release.tag) == 'string' and release.tag:match('^v%d+%.%d+%.%d+$'),
        'tag must be an immutable vMAJOR.MINOR.PATCH release')
    assert(type(release.sha256) == 'string' and #release.sha256 == 64
        and release.sha256:match('^[0-9a-f]+$'), 'sha256 must be 64 lowercase hex digits')
    return true
end

function M.render_formula(release)
    M.validate_release(release)
    local dependencies = { '  depends_on "neovim"' }
    for _, package in ipairs(deps.packages({ sysname = 'Darwin', manager = 'brew' }, 'default')) do
        assert(package:match('^[a-z0-9][a-z0-9@+._/-]*$'), 'unsafe package name in registry')
        if package ~= 'neovim' then
            dependencies[#dependencies + 1] = '  depends_on "' .. package .. '"'
        end
    end
    return string.format([[# Generated by parley.nvim packaging/formula.lua; edit the source generator.
class Parley < Formula
  desc "Isolated Neovim chat application"
  homepage "https://github.com/xianxu/parley.nvim"
  url "https://github.com/xianxu/parley.nvim/archive/refs/tags/%s.tar.gz"
  sha256 "%s"
  license "MIT"

%s

  def install
    libexec.install Dir["*", ".*"] - [".", "..", ".git"]
    (libexec/"packaging/parley").chmod 0755
    (share/"parley/config").install libexec/"packaging/starter-config/init.lua"
    (bin/"parley").write_env_script libexec/"packaging/parley",
      PARLEY_NVIM: Formula["neovim"].opt_bin/"nvim",
      PARLEY_RUNTIME: libexec,
      PARLEY_STARTER: share/"parley/config/init.lua"
  end

  test do
    ENV["XDG_CONFIG_HOME"] = (testpath/"config").to_s
    assert_match "NVIM", shell_output("#{bin}/parley --version")
    assert_path_exists testpath/"config/parley/init.lua"
  end
end
]], release.tag, release.sha256, table.concat(dependencies, '\n'))
end

return M
