local pair = require("parley.at_pair")
describe("double-at key decisions", function()
    it("falls through for single-at insertion", function()
        assert.equals("@", pair.keys("email", 5))
        assert.equals("@", pair.keys("@@word", 6))
    end)
    it("returns undo-preserving movement for generated and existing closers", function()
        assert.equals("@@@<C-g>U<Left><C-g>U<Left>", pair.keys("@", 1))
        assert.equals("@", pair.keys("@@@", 1))
        assert.equals("<C-g>U<Right>", pair.keys("@@word@@", 6))
        assert.equals("<C-g>U<Right>", pair.keys("@@word@@", 7))
    end)
end)
