-- Replaces the retired ordinal/extmark anchor contract with shared identities.
local D=require('parley.document')
describe('shared exchange identity replacing ordinal anchors',function()
    local buf,doc
    before_each(function()
        buf=vim.api.nvim_create_buf(false,true)
        vim.api.nvim_buf_set_lines(buf,0,-1,false,{'header','💬: q1','a1','a2','💬: q2','b1','b2','💬: q3','c1'})
        doc=D.attach(buf,{schedule=false})
        assert.equals('idle',D.drain(doc).status)
    end)
    after_each(function() if vim.api.nvim_buf_is_valid(buf) then vim.api.nvim_buf_delete(buf,{force=true}) end end)
    local function settle() assert.equals('idle',D.drain(doc,100000).status) end
    local function span(row)
        local result=D.exchange(doc,row)
        assert.equals('ready',result.status)
        return result
    end
    it('bounds exchanges by the next marker and the final exchange by EOF',function()
        local first,second,last=span(2),span(5),span(8)
        assert.same({1,4},{first.first,first.last})
        assert.same({4,7},{second.first,second.last})
        assert.same({7,9},{last.first,last.last})
        assert.is_not.equals(first.identity,second.identity)
    end)
    it('resolves stable handles without scanning native extmarks',function()
        local id=span(5).identity
        D.stats(doc,true)
        assert.equals(4,D.lookup(doc,id).start_row)
        assert.equals(4,D.lookup(doc,id).start_row)
        local work=D.stats(doc)
        assert.is_true(work.nodes_visited<128)
        assert.is_true(work.entries_visited<128)
    end)
    it('keeps identity across insertion and deletion before its marker',function()
        local id=span(5).identity
        vim.api.nvim_buf_set_lines(buf,2,2,false,{'inserted','prose'})
        settle();assert.equals(id,span(7).identity);assert.equals(6,D.lookup(doc,id).start_row)
        vim.api.nvim_buf_set_lines(buf,2,4,false,{})
        settle();assert.equals(id,span(5).identity);assert.equals(4,D.lookup(doc,id).start_row)
    end)
    it('retires a deleted marker instead of aliasing the next exchange',function()
        local id=span(5).identity
        vim.api.nvim_buf_set_lines(buf,4,5,false,{})
        assert.is_nil(D.lookup(doc,id));settle()
        assert.is_not.equals(id,span(5).identity)
    end)
    it('rejects a captured span when the following boundary disappears',function()
        local old=span(5)
        vim.api.nvim_buf_set_lines(buf,7,8,false,{})
        assert.is_false(D.validate_projection(doc,old.certificate))
        settle();assert.equals(8,span(5).last)
    end)
    it('preserves a surviving identity when another exchange is pruned and a new one added',function()
        local removed,survivor=span(2).identity,span(5).identity
        vim.api.nvim_buf_set_lines(buf,1,4,false,{})
        vim.api.nvim_buf_set_lines(buf,-1,-1,false,{'💬: q4','d1'})
        settle()
        assert.is_nil(D.lookup(doc,removed))
        assert.equals(survivor,span(2).identity)
        assert.is_not.equals(survivor,span(7).identity)
    end)
    it('does not resurrect an identity after identical marker replacement',function()
        local old=span(5)
        vim.api.nvim_buf_set_lines(buf,4,5,false,{'💬: q2'})
        assert.is_nil(D.lookup(doc,old.identity))
        assert.is_false(D.validate_projection(doc,old.certificate))
        settle();assert.is_not.equals(old.identity,span(5).identity)
    end)
    it('reports uncertainty before materialization rather than trusting old ordinals',function()
        vim.api.nvim_buf_set_lines(buf,0,-1,false,{'💬: replacement','body'})
        assert.is_not.equals('ready',D.exchange(doc,1).status)
        settle();assert.same({0,2},{span(1).first,span(1).last})
    end)
    it('retires every identity on detach and never aliases a newly attached document',function()
        local old=span(5)
        D.detach(doc)
        assert.is_nil(D.lookup(doc,old.identity))
        assert.equals('detached',D.exchange(doc,5).status)
        doc=D.attach(buf,{schedule=false});settle()
        assert.is_nil(D.lookup(doc,old.identity))
        assert.is_not.equals(old.identity,span(5).identity)
    end)
end)
