local sequence=require('parley.document.sequence')
local grammar=require('parley.document.grammar')
local function index(spans)
    return sequence.new(spans,{empty_summary=grammar.empty_summary(),combine=grammar.combine,
        summarize=function(m) return m and m.token and grammar.summary(m.token) or grammar.empty_summary() end})
end
local lexer
local function reply(request,line,start_byte,separator)
    local bytes=line:sub(request.col+1,request.col+request.max_bytes)
    return {request_id=request.request_id,bytes=bytes,eol=request.col+#bytes==#line,
        start_byte=start_byte,separator_bytes=separator or 0}
end

describe('bounded document lexical materializer',function()
    before_each(function() lexer=require('parley.document.lexer') end)
    it('splits one interior UTF8 row at exact byte offsets',function()
        local seq=index({{rows=3,bytes=13,opaque=true}})
        local worker=lexer.new(seq)
        lexer.demand(worker,1)
        local result=lexer.step(worker,nil,{bytes=8})
        assert.equals('read',result.status)
        result=lexer.step(worker,reply(result.request,'💬: q',3,1),{bytes=8})
        assert.equals('more',result.status)
        local spans=sequence.query(seq,0,3)
        assert.equals(3,#spans)
        assert.equals(3,spans[1].bytes)
        assert.equals(8,spans[2].bytes)
        assert.equals('user',spans[2].metadata.token.kind)
        assert.equals(2,spans[3].bytes)
        assert.equals('idle',lexer.step(worker).status)
    end)
    it('rejects a same-size replacement after a read request',function()
        local seq=index({{rows=1,bytes=5,opaque=true}})
        local worker=lexer.new(seq); lexer.demand(worker,0)
        local request=lexer.step(worker).request
        sequence.splice(seq,0,1,{{rows=1,bytes=5,opaque=true}})
        assert.equals('stale',lexer.step(worker,reply(request,'word',0,1)).status)
        assert.is_true(sequence.at(seq,0).opaque)
    end)
    it('retains lexical work across a disjoint edit that shifts the row',function()
        local seq=index({{rows=1,bytes=2,metadata={token={kind='text'}}},
            {rows=1,bytes=2,metadata={token={kind='text'}}},{rows=1,bytes=5,opaque=true}})
        local worker=lexer.new(seq); lexer.demand(worker,2)
        local request=lexer.step(worker).request
        sequence.splice(seq,0,1,{{rows=2,bytes=10,opaque=true}})
        local result=lexer.step(worker,reply(request,'word',4,1))
        assert.equals('more',result.status)
        assert.equals(3,result.published.row)
        assert.equals(12,sequence.at(seq,3).start_byte)
        assert.equals('text',sequence.at(seq,3).metadata.token.kind)
    end)
    it('refreshes an unread request when a disjoint edit moves its source',function()
        local seq=index({{rows=1,bytes=2,metadata={token={kind='text'}}},
            {rows=1,bytes=2,metadata={token={kind='text'}}},{rows=1,bytes=5,opaque=true}})
        local worker=lexer.new(seq); lexer.demand(worker,2)
        local old=lexer.step(worker).request
        sequence.splice(seq,0,1,{{rows=2,bytes=10,opaque=true}})
        local fresh=lexer.step(worker).request
        assert.equals(3,fresh.row)
        assert.is_not.equals(old.request_id,fresh.request_id)
        local result=lexer.step(worker,reply(fresh,'word',12,1))
        assert.equals('more',result.status)
        assert.equals(3,result.published.row)
    end)
    it('does not overwrite existing semantic metadata',function()
        local seq=index({{rows=1,bytes=2,metadata={token={kind='text'},semantic={exchange='keep'}}}})
        local worker=lexer.new(seq); lexer.demand(worker,0)
        assert.equals('idle',lexer.step(worker).status)
        assert.equals('keep',sequence.at(seq,0).metadata.semantic.exchange)
    end)
    it('bounds long-line reads and retained text across fragments',function()
        local line='=== '..string.rep('x',150000)..' ==='
        local seq=index({{rows=1,bytes=#line,opaque=true}})
        local worker=lexer.new(seq); lexer.demand(worker,0)
        local result=lexer.step(worker,nil,{bytes=65536})
        local reads=0
        while result.status=='read' do
            reads=reads+1
            assert.is_true(result.request.max_bytes<=65536)
            result=lexer.step(worker,reply(result.request,line,0,0),{bytes=65536})
            assert.is_true(result.work.bytes_scanned<=65536)
            assert.is_true(lexer.retained_bytes(worker)<128)
        end
        assert.equals(3,reads)
        assert.equals('more',result.status)
        assert.equals('draft_open',sequence.at(seq,0).metadata.token.kind)
    end)
    it('preserves semantic fields when adding a missing token to a confirmed row',function()
        local seq=index({{rows=1,bytes=5,metadata={semantic={exchange='keep'}}}})
        local worker=lexer.new(seq); lexer.demand(worker,0)
        local request=lexer.step(worker).request
        local input=reply(request,'word',0,1); input.separator_bytes=nil
        assert.equals('more',lexer.step(worker,input).status)
        assert.equals('keep',sequence.at(seq,0).metadata.semantic.exchange)
        assert.equals('text',sequence.at(seq,0).metadata.token.kind)
    end)
    it('conservatively rejects an adjacent boundary change',function()
        local seq=index({{rows=1,bytes=2,metadata={token={kind='text'}}},{rows=1,bytes=5,opaque=true}})
        local worker=lexer.new(seq); lexer.demand(worker,1)
        local request=lexer.step(worker).request
        sequence.splice(seq,0,1,{{rows=1,bytes=2,metadata={token={kind='text'}}}})
        assert.equals('stale',lexer.step(worker,reply(request,'word',2,1)).status)
    end)
    it('rejects responses from a replaced worker and accounts for index work',function()
        local seq=index({{rows=1,bytes=5,opaque=true}})
        local old=lexer.new(seq); lexer.demand(old,0)
        local request=lexer.step(old).request
        local fresh=lexer.new(seq); lexer.demand(fresh,0)
        local next_read=lexer.step(fresh)
        assert.is_true(next_read.work.nodes_visited>0)
        assert.not_equals(request.request_id,next_read.request.request_id)
        assert.equals('stale',lexer.step(fresh,reply(request,'word',0,1)).status)
        assert.is_true(sequence.at(seq,0).opaque)
    end)
    it('rerequests a suffix instead of retaining bytes beyond a smaller slice budget',function()
        local seq=index({{rows=1,bytes=9,opaque=true}})
        local worker=lexer.new(seq); lexer.demand(worker,0)
        local request=lexer.step(worker,nil,{bytes=1000000}).request
        assert.equals(65536,request.max_bytes)
        local result=lexer.step(worker,reply(request,'abcdefgh',0,1),{bytes=3})
        assert.equals(3,result.work.bytes_scanned)
        assert.equals(3,result.request.col)
        lexer.demand(worker,0)
        result=lexer.step(worker,reply(result.request,'abcdefgh',0,1),{bytes=3})
        assert.equals(6,result.request.col)
        result=lexer.step(worker,reply(result.request,'abcdefgh',0,1),{bytes=3})
        assert.equals('more',result.status)
        assert.equals(1,result.work.rows_materialized)
    end)

end)
