local Runner=require('tests.helpers.spec_runner')
describe('scoped test timeouts',function()
    it('extends only the real large conformance corpora',function()
        local path='tests/integration/document_fold_batches_spec.lua'
        assert.same({timeout=180000,sequential=true},Runner.options(path))
        assert.same(Runner.options(path),Runner.options(vim.fn.fnamemodify(path,':p')))
        assert.same({timeout=180000,sequential=true},Runner.options('tests/unit/document_semantic_spec.lua'))
        assert.same({timeout=180000,sequential=true},Runner.options('tests/integration/document_fold_retirement_spec.lua'))
        assert.same({timeout=180000,sequential=true},Runner.options('tests/integration/document_fold_uncertainty_retirement_spec.lua'))
        assert.is_nil(Runner.options('tests/integration/document_folds_spec.lua'))
        assert.is_nil(Runner.options('tests/unit/document_fold_batches_spec.lua'))
        assert.is_nil(Runner.options('/another/repository/tests/integration/document_fold_batches_spec.lua'))
    end)
    it('stretches the deadline by oversubscription, never below 1x or above the cap',function()
        assert.equals(1,Runner.load_factor(0,12))
        assert.equals(1,Runner.load_factor(12,12))
        assert.equals(2.5,Runner.load_factor(30,12))
        assert.equals(4,Runner.load_factor(105,12))
        assert.equals(4,Runner.load_factor(5,0)) -- a zero CPU count cannot divide by zero
    end)
end)
