local starter

describe('starter profile options', function()
    before_each(function() starter = require('parley.starter_config') end)
    it('retains product search terms for the app providers', function()
        local opts = starter.options({ data = '/profile/data', state = '/profile/state' })
        assert.same({'claude:opus,sonnet,fable', 'codex:gpt-6,gpt-5', 'gemini'},
            opts.cliproxy.live_models.providers)
    end)
    it('keeps chat prefix and Alt chords without enabling other shortcut families', function()
        local opts = starter.options({ data = '/profile/data', state = '/profile/state' })
        assert.same({ '<C-g>f' }, opts.global_shortcut_finder.shortcut)
        assert.same({ '<C-g>?' }, opts.global_shortcut_keybindings.shortcut)
        assert.same({ '<C-g><C-g>', '<M-CR>' }, opts.chat_shortcut_respond.shortcut)
        assert.same({ '<M-o>', '<C-g>o' }, opts.chat_shortcut_open_file.shortcut)
        assert.same({ '<C-g>t', '<M-t>' }, opts.chat_shortcut_outline.shortcut)
        assert.same({ '<M-v>' }, opts.chat_shortcut_paste_image.shortcut)
        assert.is_nil(opts.global_shortcut_issue_finder)
        assert.is_nil(opts.global_shortcut_note_finder)
        assert.is_false(opts.default_keymaps)
    end)
    it('replaces inherited personal paths, providers and tools', function()
        local roots = { data = '/profile/data', state = '/profile/state' }
        local opts = starter.options(roots)
        assert.equals('/profile/data/chats', opts.chat_dir)
        assert.same({}, opts.chat_dirs)
        assert.equals('/profile/state/persisted', opts.state_dir)
        assert.equals('/profile/data/auth', opts.cliproxy.auth_dir)
        assert.same({ cliproxyapi = 'parley-local' }, opts.api_keys)
        assert.same({}, opts.providers.openai)
        assert.same({}, opts.providers.anthropic)
        assert.same({}, opts.providers.googleai)
        assert.same({}, opts.providers.ollama)
        assert.equals('http://127.0.0.1:8317/v1/chat/completions', opts.providers.cliproxyapi.endpoint)
        assert.same({'parley_help', 'read_file', 'ls', 'find', 'grep', 'chat_history_search', 'write_file', 'edit_file'}, opts.cliproxy.live_models.tools)
        assert.is_true(opts.cliproxy.manage)
        assert.is_true(opts.cliproxy.auto_download)
        assert.is_false(opts.web_search)
        assert.is_false(opts.default_keymaps)
        assert.is_false(opts.memory_prefs.enable)
        assert.is_false(opts.chat_memory.enable)
        assert.same({}, opts.tool_read_roots)
        assert.is_true(opts.agents[1].disable)
        assert.same({'parley_help', 'read_file', 'ls', 'find', 'grep', 'chat_history_search', 'write_file', 'edit_file'}, opts.agents[2].tools)
        assert.is_true(opts.chat_confirm_delete)
    end)
end)
