local starter

describe('starter profile options', function()
    before_each(function() starter = require('parley.starter_config') end)
    it('inherits common learner behavior instead of carrying a second policy', function()
        local defaults = require('parley.config')
        local opts = starter.options({data = '/profile/data', state = '/profile/state'})
        assert.is_nil(opts.agents)
        assert.is_nil(opts.cliproxy)
        assert.is_nil(opts.chat_memory)
        assert.is_nil(opts.web_search)
        assert.is_false(defaults.chat_memory.enable)
        assert.is_true(defaults.web_search)
        assert.is_true(defaults.agents[1].placeholder)
        assert.equals('Choose a model', defaults.agents[1].name)
        assert.matches('We collaboratively seek knowledge', defaults.agents[1].system_prompt)
        assert.is_truthy(defaults.agents[1].system_prompt:find('always generate summary', 1, true))
    end)
    it('retains product search terms for the app providers', function()
        local opts = starter.options({ data = '/profile/data', state = '/profile/state' })
        assert.same({'claude:opus,sonnet,fable', 'codex:gpt-6,gpt-5', 'gemini'},
            require('parley.config').cliproxy.live_models.providers)
    end)
    it('keeps chat prefix and Alt chords without enabling other shortcut families', function()
        local opts = starter.options({ data = '/profile/data', state = '/profile/state' })
        assert.same({ '<C-g>f' }, opts.global_shortcut_finder.shortcut)
        assert.same({ '<C-g>?' }, opts.global_shortcut_keybindings.shortcut)
        assert.same({ '<C-g><C-g>', '<M-CR>' }, opts.chat_shortcut_respond.shortcut)
        assert.same({ '<M-o>', '<C-g>o' }, opts.chat_shortcut_open_file.shortcut)
        assert.same({ '<C-g>t', '<M-t>' }, opts.chat_shortcut_outline.shortcut)
        assert.same({ '<M-v>' }, opts.chat_shortcut_paste_image.shortcut)
        assert.is_nil(opts.global_shortcut_issue_finder)
        assert.is_nil(opts.global_shortcut_note_finder)
        assert.is_false(opts.default_keymaps)
    end)
    it('overrides app locations and external provider availability only', function()
        local roots = { data = '/profile/data', state = '/profile/state' }
        local opts = starter.options(roots)
        assert.equals('/profile/data/chats', opts.chat_dir)
        assert.same({}, opts.chat_dirs)
        assert.equals('/profile/state/persisted', opts.state_dir)
        assert.same({}, opts.providers.openai)
        assert.same({}, opts.providers.anthropic)
        assert.same({}, opts.providers.googleai)
        assert.same({}, opts.providers.ollama)
        assert.same({cliproxyapi = require('parley.config').api_keys.cliproxyapi}, opts.api_keys)
        assert.same(require('parley.config').providers.cliproxyapi, opts.providers.cliproxyapi)
        local common = require('parley.config')
        assert.equals(vim.fn.expand('~/.cli-proxy-api'), common.cliproxy.auth_dir)
        assert.same({'@all'},
            common.cliproxy.live_models.tools)
        assert.same(common.cliproxy.live_models.tools, common.agents[1].tools)
        assert.is_true(common.cliproxy.manage)
        assert.is_true(common.cliproxy.auto_download)
        assert.is_false(common.memory_prefs.enable)
        assert.same({}, common.tool_read_roots)
        assert.is_true(common.chat_confirm_delete)
        assert.matches('/parley/chats$', common.chat_dir)
        assert.matches('/parley/notes$', common.notes_dir)
        assert.matches('/parley/exports/html$', common.export_html_dir)
    end)
end)
