local starter

describe('starter profile options', function()
    before_each(function() starter = require('parley.starter_config') end)
    it('replaces inherited personal paths, providers and tools', function()
        local roots = { data = '/profile/data', state = '/profile/state' }
        local opts = starter.options(roots, 'client-key')
        assert.equals('/profile/data/chats', opts.chat_dir)
        assert.equals('/profile/state/persisted', opts.state_dir)
        assert.equals('/profile/data/auth', opts.cliproxy.auth_dir)
        assert.same({ cliproxyapi = 'client-key' }, opts.api_keys)
        assert.same({}, opts.providers.openai)
        assert.same({}, opts.providers.anthropic)
        assert.same({}, opts.providers.googleai)
        assert.same({}, opts.providers.ollama)
        assert.equals('http://127.0.0.1:8318/v1/chat/completions', opts.providers.cliproxyapi.endpoint)
        assert.same({}, opts.cliproxy.live_models.tools)
        assert.is_true(opts.cliproxy.manage)
        assert.is_true(opts.cliproxy.auto_download)
        assert.is_false(opts.web_search)
        assert.is_false(opts.default_keymaps)
        assert.is_false(opts.memory_prefs.enable)
        assert.same({}, opts.tool_read_roots)
        assert.is_true(opts.agents[1].disable)
        assert.same({}, opts.agents[2].tools)
        assert.is_true(opts.chat_confirm_delete)
    end)
end)
