local Policy=require('parley.tools.traversal_policy')
describe('mandatory traversal exclusion policy',function()
    it('places the mandatory rg exclusion after every optional glob',function()
        local original={'rg','--glob','**/*','--','secret','.'}
        local command=assert(Policy.apply(original,'/root/private','/root'))
        assert.same({'rg','--glob','**/*','--glob','!**/private/**','--','secret','.'},command)
        assert.equals(6,#original)
    end)
    it('escapes literal private names separately for rg and find patterns',function()
        local rg=assert(Policy.apply({'rg','--','x','.'},'/root/[p]*?','/root'))
        assert.equals('!**/\\[p\\]\\*\\?/**',rg[3])
        local find=assert(Policy.apply({'find','.','-name','*'},'/root/[p]*?','/root'))
        assert.equals('./[[]p[]][*][?]',find[5])
    end)
    it('keeps grep directory excludes independent from filename includes',function()
        local command=assert(Policy.apply({'grep','--include','*','--','x','.'},'/root/[p]*?','/root'))
        assert.equals('--exclude-dir=[[]p[]][*][?]',command[4])
    end)
    it('uses exact ack directory matching after optional filters',function()
        local command=assert(Policy.apply({'ack','--type=lua','--','x','.'},'/root/[p]*?','/root'))
        assert.equals('--ignore-dir=is:[p]*?',command[3])
    end)
    it('refuses recursive ls overlap and direct private targets',function()
        assert.is_nil(Policy.apply({'ls','-laR','.'},'/root/private','/root'))
        assert.is_nil(Policy.apply({'find','.'},'/root/private','/root/private'))
        assert.is_truthy(Policy.apply({'ls','-la','.'},'/root/private','/root'))
    end)
    it('does not alter disjoint pinned targets',function()
        local command={'rg','--glob','**/*','--','x','.'}
        assert.same(command,Policy.apply(command,'/other/private','/root'))
    end)
    it('protects private descendants when the captured traversal root is slash',function()
        local command=assert(Policy.apply({'rg','--','x','.'},'/state/private','/'))
        assert.equals('!**/state/private/**',command[3])
    end)

end)
