local Scope=require('parley.tools.process_scope')
describe('captured subprocess target planning',function()
    it('splits search roots without treating pattern data as a path',function()
        local plans=assert(Scope.plan({'rg','-H','--','/allowed/pattern','/allowed/a','/allowed/b'}))
        assert.equals(2,#plans);assert.equals('/allowed/a',plans[1].path)
        assert.same({'rg','-H','--','/allowed/pattern','.'},plans[1].command)
        assert.equals('/allowed/b',plans[2].path)
    end)
    it('retains find predicates and exact target identity',function()
        local plans=assert(Scope.plan({'find','/allowed/a','-name','*.lua'}))
        assert.equals('/allowed/a',plans[1].path)
        assert.same({'find','.','-name','*.lua'},plans[1].command)
    end)
    it('rejects unknown traversal commands and missing explicit targets',function()
        assert.is_nil(Scope.plan({'sh','-c','ls'}))
        assert.is_nil(Scope.plan({'rg','--','pattern'}))
    end)
    it('restores only leading output path labels',function()
        local text='./a:2: text ./keep\n.:\n./b\n'
        assert.equals('/allowed/a:2: text ./keep\n/allowed:\n/allowed/b\n',Scope.restore(text,'/allowed'))
    end)
    it('preserves errors across later empty search roots',function()
        assert.equals(2,Scope.join_code(2,1))
        assert.equals(0,Scope.join_code(0,1))
        assert.equals(0,Scope.join_code(1,0))
        assert.equals(1,Scope.join_code(nil,1))
    end)

    it('bounds expanded path labels and reports omitted output',function()
        local text,truncated=Scope.restore('./a\n./b\n','/very/long/path',nil,10)
        assert.equals(10,#text);assert.is_true(truncated)
        local empty,omitted=Scope.restore('./a','/allowed',nil,0)
        assert.equals('',empty);assert.is_true(omitted)
    end)

    it('keeps private rg exclusions relative to the pinned target',function()
        local plan=assert(Scope.plan({'rg','--glob','!**/allowed/private/**','--','secret','/allowed'},'/allowed/private'))[1]
        assert.equals('!**/private/**',plan.command[3])
    end)

end)
