describe('shared file transformations',function()
    local T
    before_each(function()T=require('parley.tools.file_transform')end)
    it('replaces literal percent and pattern characters consistently',function()
        local bytes,msg=T.transform('edit_file',{old_string='a.b',new_string='%1',replace_all=true},'a.b a.b','/file',100)
        assert.equals('%1 %1',bytes);assert.equals('Replaced 2 occurrence(s) in /file',msg)
    end)
    it('preserves terminal newline and clamps insertion position',function()
        local bytes=T.transform('edit_file',{insert_line=99,insert_text='two\n'},'one\n','/file',100)
        assert.equals('one\ntwo\n',bytes)
        assert.equals('zero\none',T.transform('edit_file',{insert_line=-2,insert_text='zero'},'one','/file',100))
    end)
    it('refuses ambiguous replacement and oversized transformations',function()
        assert.is_nil(T.transform('edit_file',{old_string='a',new_string='b'},'aa','/file',100))
        assert.is_nil(T.transform('edit_file',{old_string='a',new_string='long',replace_all=true},'aa','/file',4))
        assert.is_nil(T.transform('write_file',{content='large'},'','/file',4))
    end)
    it('delegates atomic proposals without changing input',function()
        local edits={{old_string='one',new_string='two',explain='rename'}}
        assert.equals('two',T.transform('propose_edits',{edits=edits},'one','/file',100))
        assert.equals('one',edits[1].old_string)
    end)
    it('numbers only the requested lines and rejects invalid ranges',function()
        assert.equals('    2  two',T.numbered_read({offset=2,limit=1},'one\ntwo\nthree\n'))
        assert.equals('    2  two',T.numbered_read({line_start=2,line_end=2},'one\ntwo\n'))
        assert.equals('',T.numbered_read({},''))
        assert.is_nil(T.numbered_read({offset=0},'one'))
    end)
end)
